obj-$(CONFIG_CDFINGER_FP)	+= cdfingerfp/
# Huaqin add for ZQL1820-42 by puqirui at 2018/08/02 start
obj-$(CONFIG_FOCALTECH_FP)	+= focaltech/
# Huaqin add for ZQL1820-42 by puqirui at 2018/08/02 end

# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 start
obj-$(CONFIG_GOODIX_FP)	+= goodixfp/
# Huaqin add for ZQL1650-143 by wangxiang at 2018/02/09 end

obj-$(CONFIG_COMMON_FP)	+= common/
